# Generated by Django 5.0.3 on 2024-03-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceconnectapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='provider_logos/')),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('payment_methods', models.CharField(blank=True, max_length=255)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('certifications', models.TextField(blank=True)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'provider',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('providers', models.ManyToManyField(related_name='services', to='serviceconnectapp.provider')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'service',
                'managed': True,
            },
        ),
    ]
