# Generated by Django 5.0.3 on 2024-03-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceconnectapp', '0003_provider_category_description_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='special',
            field=models.BooleanField(default=False),
        ),
    ]
