# Generated by Django 5.0.3 on 2024-03-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serviceconnectapp', '0006_rename_image_special_spec_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Special',
        ),
    ]
