# Generated by Django 5.0.3 on 2024-03-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceconnectapp', '0008_service_automobile_service_beauty_service_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='providers',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='pix.png', null=True, upload_to='food'),
        ),
    ]
